swagger: '2.0'
info:
  version: '1.0'
  title: Dial Code API
  description: >-
    DIAL Code is an unique code which can be used to link with Content and
    further can ve used to get the content. DIAL Code can be generated and
    maintained using DIAL Code APIs.
  license:
    name: EkStep License
    url: 'http:www.EkStep.in'
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: 'http://example.com'
    scopes: {}
    x-skip-client-authentication: false
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /dialcode/v3/generate:
    post:
      description: >-
        API to generate DIAL codes for a given publisher. Max DIAL codes
        generated by this API is 1000.
      summary: Dial Code - Generate
      tags:
        - Misc
      operationId: DialcodeV3GeneratePost
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Dial code  generaterequest'
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: X-Channel-Id
          in: header
          required: true
          type: string
          description: ''
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security: []
      x-unitTests:
        - request:
            method: POST
            uri: /dialcode/v3/generate
            headers:
              Content-Type: application/json
              X-Channel-Id: channelTest
              Authorization: '{{APIKey}}'
            body: |-
              {
                "request": {
                    "dialcodes": {
                      "count":2,
                      "publisher": "testpub01"
                    }
                }
              }
          expectedResponse:
            x-allowExtraHeaders: true
            x-bodyMatchMode: NONE
            x-arrayOrderedMatching: false
            x-arrayCheckCount: false
            x-matchResponseSchema: true
            headers: {}
          x-testShouldPass: true
          x-testEnabled: true
          x-testName: Dial Code - Generate
          x-testDescription: >-
            API to generate DIAL codes for a given publisher. Max DIAL codes
            generated by this API is 1000.
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/dialcode/v3/read/{dialcodeId}':
    get:
      description: API to fetch information about a specific DIAL code.
      summary: Dial Code - Read
      tags:
        - Misc
      operationId: DialcodeV3ReadByDialcodeIdGet
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
        - name: dialcodeId
          in: path
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/dialcode/v3/update/{dialcodeId}':
    patch:
      description: API to update a metadata of the given DIAL code.
      summary: DialCode - Update
      tags:
        - Misc
      operationId: DialcodeV3UpdateByDialcodeIdPatch
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Dialcode  updaterequest'
        - name: X-Channel-Id
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
        - name: dialcodeId
          in: path
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /dialcode/v3/list:
    post:
      description: To get the DIAL codes of a publisher (required).
      summary: Dial Code - List
      tags:
        - Misc
      operationId: DialcodeV3ListPost
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Dial code  listrequest'
        - name: X-Channel-Id
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security: []
      x-unitTests:
        - request:
            method: POST
            uri: /dialcode/v3/list
            headers:
              Content-Type: application/json
              X-Channel-Id: channelKA
              Authorization: '{{APIKey}}'
            body: |-
              {
                "request": { 
                  "search": {
                    "publisher":"testpub01"
                  }
                }
              }
          expectedResponse:
            x-allowExtraHeaders: true
            x-bodyMatchMode: NONE
            x-arrayOrderedMatching: false
            x-arrayCheckCount: false
            x-matchResponseSchema: true
            headers: {}
          x-testShouldPass: true
          x-testEnabled: true
          x-testName: Dial Code - List
          x-testDescription: To get the DIAL codes of a publisher (required).
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/dialcode/v3/publish/{dialcodeId}':
    post:
      description: API to freeze the changes on a DIAL code.
      summary: Dial Code - Publish
      tags:
        - Misc
      operationId: DialcodeV3PublishByDialcodeIdPost
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Dial code  publishrequest'
        - name: X-Channel-Id
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
        - name: dialcodeId
          in: path
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security:
        - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /content/v3/dialcode/link:
    post:
      description: API to link content(s) with DIAL code(s).
      summary: Content - Link DIAL code
      tags:
        - Misc
      operationId: ContentV3DialcodeLinkPost
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/Content  link dial coderequest'
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: user-id
          in: header
          required: true
          type: string
          description: ''
        - name: Authorization
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
      security: []
      x-unitTests:
        - request:
            method: POST
            uri: /content/v3/dialcode/link
            headers:
              Content-Type: application/json
              user-id: ekstep
              Authorization: 'Bearer {{api_key}}'
            body: |-
              {
                "request": {
                  "content": {
                    "identifier": [],
                    "dialcode": []
                    
                  }
                }
              }
          expectedResponse:
            x-allowExtraHeaders: true
            x-bodyMatchMode: NONE
            x-arrayOrderedMatching: false
            x-arrayCheckCount: false
            x-matchResponseSchema: true
            headers: {}
          x-testShouldPass: true
          x-testEnabled: true
          x-testName: Content - Link DIAL code
          x-testDescription: API to link content(s) with DIAL code(s).
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  Dial code  generaterequest:
    title: Dial Code - GenerateRequest
    example:
      request:
        dialcodes:
          count: 2
          publisher: testpub01
    type: object
    properties:
      request:
        $ref: '#/definitions/Request'
    required:
      - request
  Request:
    title: Request
    example:
      dialcodes:
        count: 2
        publisher: testpub01
    type: object
    properties:
      dialcodes:
        $ref: '#/definitions/Dialcodes'
    required:
      - dialcodes
  Dialcodes:
    title: Dialcodes
    example:
      count: 2
      publisher: testpub01
    type: object
    properties:
      count:
        description: ''
        example: 2
        type: integer
        format: int32
      publisher:
        description: ''
        example: testpub01
        type: string
    required:
      - count
      - publisher
  Dialcode  updaterequest:
    title: DialCode - UpdateRequest
    example:
      request:
        dialcode:
          metadata:
            class: std2
            subject: Math
            board: CBSE
    type: object
    properties:
      request:
        $ref: '#/definitions/Request4'
    required:
      - request
  Request4:
    title: Request4
    example:
      dialcode:
        metadata:
          class: std2
          subject: Math
          board: CBSE
    type: object
    properties:
      dialcode:
        $ref: '#/definitions/Dialcode'
    required:
      - dialcode
  Dialcode:
    title: Dialcode
    example:
      metadata:
        class: std2
        subject: Math
        board: CBSE
    type: object
    properties:
      metadata:
        $ref: '#/definitions/Metadata'
    required:
      - metadata
  Metadata:
    title: Metadata
    example:
      class: std2
      subject: Math
      board: CBSE
    type: object
    properties:
      class:
        description: ''
        example: std2
        type: string
      subject:
        description: ''
        example: Math
        type: string
      board:
        description: ''
        example: CBSE
        type: string
    required:
      - class
      - subject
      - board
  Dial code  listrequest:
    title: Dial Code - ListRequest
    example:
      request:
        search:
          publisher: testpub01
    type: object
    properties:
      request:
        $ref: '#/definitions/Request8'
    required:
      - request
  Request8:
    title: Request8
    example:
      search:
        publisher: testpub01
    type: object
    properties:
      search:
        $ref: '#/definitions/Search'
    required:
      - search
  Search:
    title: Search
    example:
      publisher: testpub01
    type: object
    properties:
      publisher:
        description: ''
        example: testpub01
        type: string
    required:
      - publisher
  Dial code  publishrequest:
    title: Dial Code - PublishRequest
    example:
      request: {}
    type: object
    properties:
      request:
        description: ''
        example: {}
        type: object
    required:
      - request
  Content  link dial coderequest:
    title: Content - Link DIAL codeRequest
    example:
      request:
        content:
          identifier: []
          dialcode: []
    type: object
    properties:
      request:
        $ref: '#/definitions/Request12'
    required:
      - request
  Request12:
    title: Request12
    example:
      content:
        identifier: []
        dialcode: []
    type: object
    properties:
      content:
        $ref: '#/definitions/Content'
    required:
      - content
  Content:
    title: Content
    example:
      identifier: []
      dialcode: []
    type: object
    properties:
      identifier:
        description: ''
        example: []
        type: array
        items:
          type: string
      dialcode:
        description: ''
        example: []
        type: array
        items:
          type: string
    required:
      - identifier
      - dialcode
